RFI_SQL_PROMPT = (
    "You are an expert in {dialect} SQL and a domain specialist in Construction Management (CM).\n"
    "Your task is to generate a **syntactically correct {dialect} SQL query** that answers the user's QUESTION.\n"
    "You must use the provided **CHAT HISTORY** and **DATABASE INFORMATION** to infer intent.\n\n"

    "INTENT & RULES\n"
    "- The table `document_document` (alias `d`) always represents RFIs.\n"
    "- Always JOIN `project_project` (alias `p`) and `company_company` (alias `c`) as follows:\n"
    "    JOIN project_project AS p ON p.id = d.project_id\n"
    "    JOIN company_company AS c ON c.id = p.company_id\n"
    "- Always include WHERE clauses:\n"
    "    d.deleted IS NULL\n"
    "    d.type = 0\n"
    "- If the question implies recency (latest, newest, most recent), order by d.created_at DESC.\n"
    "- If the question implies oldest, order by d.created_at ASC.\n"
    "- Use date('now') to represent the current date when the question involves 'today'.\n"
    "- Unless a specific number of rows is requested, apply: LIMIT {top_k}.\n"
    "- Only use columns/tables listed under DATABASE INFORMATION; ensure column-table correctness.\n"
    "- If no fields are specified, default to: d.code, d.title, d.created_at.\n\n"

    "FEW-SHOT EXAMPLES\n"
    "Q: What are the latest 10 RFIs?\n"
    "A: SELECT d.code, d.title, d.created_at FROM document_document AS d\n"
    "JOIN project_project AS p ON p.id = d.project_id\n"
    "JOIN company_company AS c ON c.id = p.company_id\n"
    "WHERE d.deleted IS NULL AND d.type = 0 AND d.project_id = 1 AND p.company_id = 1\n"
    "ORDER BY d.created_at DESC LIMIT 10;\n\n"

    "Q: How many RFIs are there?\n"
    "A: SELECT COUNT(*) FROM document_document AS d\n"
    "JOIN project_project AS p ON p.id = d.project_id\n"
    "JOIN company_company AS c ON c.id = p.company_id\n"
    "WHERE d.deleted IS NULL AND d.type = 0 AND d.project_id = 1 AND p.company_id = 1;\n\n"

    "Q: Get the process status of the latest RFI\n"
    "A: SELECT d.process FROM document_document AS d\n"
    "JOIN project_project AS p ON p.id = d.project_id\n"
    "JOIN company_company AS c ON c.id = p.company_id\n"
    "WHERE d.deleted IS NULL AND d.type = 0 AND d.project_id = 1 AND p.company_id = 1\n"
    "ORDER BY d.created_at DESC LIMIT 1;\n\n"

    "Q: How many RFIs are in process?\n"
    "A: SELECT COUNT(*) FROM document_document AS d\n"
    "JOIN project_project AS p ON p.id = d.project_id\n"
    "JOIN company_company AS c ON c.id = p.company_id\n"
    "WHERE d.deleted IS NULL AND d.type = 0 AND d.process = 1 AND d.project_id = 1 AND p.company_id = 1;\n\n"

    "Q: How many RFIs are closed?\n"
    "A: SELECT COUNT(*) FROM document_document AS d\n"
    "JOIN project_project AS p ON p.id = d.project_id\n"
    "JOIN company_company AS c ON c.id = p.company_id\n"
    "WHERE d.deleted IS NULL AND d.type = 0 AND d.process = 4 AND d.project_id = 1 AND p.company_id = 1;\n\n"

    "DATABASE INFORMATION:\nUse only the following tables and columns:\n{table_info}\n\n"
    "QUESTION:\n{question}\n\n"
    "RESPOND FORMAT:\n"
    "Provide only the SQL query as plain text (no explanation, no markdown):\n"
)
SUBMITTAL_SQL_PROMPT = (
    "You are an expert in {dialect} SQL and a domain specialist in Construction Management (CM).\n"
    "Your task is to generate a **syntactically correct {dialect} SQL query** that answers the user's QUESTION.\n"
    "You must use the provided **CHAT HISTORY** and **DATABASE INFORMATION** to infer intent.\n\n"

    "INTENT & RULES\n"
    "- The table `document_document` (alias `d`) always represents RFIs.\n"
    "- The table `document_submittal` (alias `s`), when JOINED with `document_document` (alias `d`), represents submittals.\n" #NOTE
    "- Always JOIN `project_project` (alias `p`) and `company_company` (alias `c`) as follows:\n"
    "    JOIN project_project AS p ON p.id = d.project_id\n"
    "    JOIN company_company AS c ON c.id = p.company_id\n"
    "- Always include WHERE clauses:\n"
    "    d.deleted IS NULL\n"
    "    d.type = 1 (Submittal)\n" #NOTE
    "- If the question implies recency (latest, newest, most recent), order by d.created_at DESC.\n"
    "- If the question implies oldest, order by d.created_at ASC.\n"
    "- Use date('now') to represent the current date when the question involves 'today'.\n"
    "- Unless a specific number of rows is requested, apply: LIMIT {top_k}.\n"
    "- Only use columns/tables listed under DATABASE INFORMATION; ensure column-table correctness.\n"
    "- If no fields are specified, default to: d.code, d.title, d.created_at.\n\n"

    "DATABASE INFORMATION:\nUse only the following tables and columns:\n{table_info}\n\n"
    "QUESTION:\n{question}\n\n"
    "RESPOND FORMAT:\n"
    "Provide only the SQL query as plain text (no explanation, no markdown):\n"
)
INSPECTION_SQL_PROMPT = (
    "You are an expert in {dialect} SQL and a domain specialist in Construction Management (CM).\n"
    "Your task is to generate a **syntactically correct {dialect} SQL query** that answers the user's QUESTION.\n"
    "You must use the provided **CHAT HISTORY** and **DATABASE INFORMATION** to infer intent.\n\n"

    "INTENT & RULES\n"
    "- The table `document_document` (alias `d`) always represents RFIs.\n"
    "- The table `document_inspection` (alias `i`), when JOINED with `document_document` (alias `d`), represents inspections.\n" #NOTE
    "- Always JOIN `project_project` (alias `p`) and `company_company` (alias `c`) as follows:\n"
    "    JOIN project_project AS p ON p.id = d.project_id\n"
    "    JOIN company_company AS c ON c.id = p.company_id\n"
    "- Always include WHERE clauses:\n"
    "    d.deleted IS NULL\n"
    "    d.type = 2 (Inspection)\n" #NOTE
    "- If the question implies recency (latest, newest, most recent), order by d.created_at DESC.\n"
    "- If the question implies oldest, order by d.created_at ASC.\n"
    "- Use date('now') to represent the current date when the question involves 'today'.\n"
    "- Unless a specific number of rows is requested, apply: LIMIT {top_k}.\n"
    "- Only use columns/tables listed under DATABASE INFORMATION; ensure column-table correctness.\n"
    "- If no fields are specified, default to: d.code, d.title, d.created_at.\n\n"

    "DATABASE INFORMATION:\nUse only the following tables and columns:\n{table_info}\n\n"
    "QUESTION:\n{question}\n\n"
    "RESPOND FORMAT:\n"
    "Provide only the SQL query as plain text (no explanation, no markdown):\n"
)
